<?php

namespace Database\Seeders;

use App\Models\Bank;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BanksTableSeeder extends Seeder
{
    public function run()
    {
        Bank::create(['bank_code' => 332, 'name' => ucwords(strtolower('Acesso Soluções de Pagamento S.A.               								')), 'short_name' => ucwords(strtolower('Banco Acesso                  				')),]);
        Bank::create(['bank_code' => 654, 'name' => ucwords(strtolower('Banco A. J. Renner S.A.															')), 'short_name' => ucwords(strtolower('Banco Renner								')),]);
        Bank::create(['bank_code' => 246, 'name' => ucwords(strtolower('Banco ABC Brasil S.A.															')), 'short_name' => ucwords(strtolower('Banco ABC Brasil							')),]);
        Bank::create(['bank_code' => 75, 'name' => ucwords(strtolower('Banco ABN Amro S.A.																')), 'short_name' => ucwords(strtolower('Banco ABN Amro								')),]);
        Bank::create(['bank_code' => 121, 'name' => ucwords(strtolower('Banco Agibank S.A.																')), 'short_name' => ucwords(strtolower('Banco Agibank								')),]);
        Bank::create(['bank_code' => 25, 'name' => ucwords(strtolower('Banco Alfa S.A.																	')), 'short_name' => ucwords(strtolower('Banco Alfa									')),]);
        Bank::create(['bank_code' => 65, 'name' => ucwords(strtolower('Banco AndBank (Brasil) S.A.														')), 'short_name' => ucwords(strtolower('Banco AndBank (Brasil)						')),]);
        Bank::create(['bank_code' => 213, 'name' => ucwords(strtolower('Banco Arbi S.A.																	')), 'short_name' => ucwords(strtolower('Banco Arbi									')),]);
        Bank::create(['bank_code' => 96, 'name' => ucwords(strtolower('Banco B3 S.A.      																')), 'short_name' => ucwords(strtolower('Banco B3    								')),]);
        Bank::create(['bank_code' => 24, 'name' => ucwords(strtolower('Banco Bandepe S.A.																')), 'short_name' => ucwords(strtolower('Banco Bandepe								')),]);
        Bank::create(['bank_code' => 330, 'name' => ucwords(strtolower('Banco Bari de Investimentos e Financiamentos S.A								')), 'short_name' => ucwords(strtolower('Banco Bari									')),]);
        Bank::create(['bank_code' => 318, 'name' => ucwords(strtolower('Banco BMG S.A.																	')), 'short_name' => ucwords(strtolower('Banco BMG									')),]);
        Bank::create(['bank_code' => 752, 'name' => ucwords(strtolower('Banco BNP Paribas Brasil S.A.													')), 'short_name' => ucwords(strtolower('Banco BNP Paribas Brasil					')),]);
        Bank::create(['bank_code' => 107, 'name' => ucwords(strtolower('Banco Bocom BBM S.A.															')), 'short_name' => ucwords(strtolower('Banco Bocom BBM							')),]);
        Bank::create(['bank_code' => 63, 'name' => ucwords(strtolower('Banco Bradescard S.A.															')), 'short_name' => ucwords(strtolower('Banco Bradescard							')),]);
        Bank::create(['bank_code' => 36, 'name' => ucwords(strtolower('Banco Bradesco BBI S.A.															')), 'short_name' => ucwords(strtolower('Banco Bradesco BBI							')),]);
        Bank::create(['bank_code' => 122, 'name' => ucwords(strtolower('Banco Bradesco BERJ S.A.														')), 'short_name' => ucwords(strtolower('Banco Bradesco BERJ						')),]);
        Bank::create(['bank_code' => 204, 'name' => ucwords(strtolower('Banco Bradesco Cartões S.A.														')), 'short_name' => ucwords(strtolower('Banco Bradesco Cartões						')),]);
        Bank::create(['bank_code' => 394, 'name' => ucwords(strtolower('Banco Bradesco Financiamentos S.A.												')), 'short_name' => ucwords(strtolower('Banco Bradesco Financiamentos				')),]);
        Bank::create(['bank_code' => 237, 'name' => ucwords(strtolower('Banco Bradesco S.A.																')), 'short_name' => ucwords(strtolower('Banco Bradesco								')),]);
        Bank::create(['bank_code' => 218, 'name' => ucwords(strtolower('Banco BS2 S.A.																	')), 'short_name' => ucwords(strtolower('Banco BS2									')),]);
        Bank::create(['bank_code' => 208, 'name' => ucwords(strtolower('Banco BTG Pactual S.A.															')), 'short_name' => ucwords(strtolower('Banco BTG Pactual							')),]);
        Bank::create(['bank_code' => 336, 'name' => ucwords(strtolower('Banco C6 S.A.																	')), 'short_name' => ucwords(strtolower('Banco C6									')),]);
        Bank::create(['bank_code' => 473, 'name' => ucwords(strtolower('Banco Caixa Geral - Brasil S.A.													')), 'short_name' => ucwords(strtolower('Banco Caixa Geral - Brasil					')),]);
        Bank::create(['bank_code' => 412, 'name' => ucwords(strtolower('Banco Capital S. A.																')), 'short_name' => ucwords(strtolower('Banco Capital								')),]);
        Bank::create(['bank_code' => 40, 'name' => ucwords(strtolower('Banco Cargill S.A.																')), 'short_name' => ucwords(strtolower('Banco Cargill								')),]);
        Bank::create(['bank_code' => 266, 'name' => ucwords(strtolower('Banco Cédula S.A.																')), 'short_name' => ucwords(strtolower('Banco Cédula 								')),]);
        Bank::create(['bank_code' => 739, 'name' => ucwords(strtolower('Banco Cetelem S.A.																')), 'short_name' => ucwords(strtolower('Banco Cetelem								')),]);
        Bank::create(['bank_code' => 233, 'name' => ucwords(strtolower('Banco Cifra S.A.																')), 'short_name' => ucwords(strtolower('Banco Cifra								')),]);
        Bank::create(['bank_code' => 745, 'name' => ucwords(strtolower('Banco Citibank S.A.																')), 'short_name' => ucwords(strtolower('Banco Citibank S.A.						')),]);
        Bank::create(['bank_code' => 241, 'name' => ucwords(strtolower('Banco Clássico S.A.																')), 'short_name' => ucwords(strtolower('Banco Clássico S.A.						')),]);
        Bank::create(['bank_code' => 756, 'name' => ucwords(strtolower('Banco Cooperativo do Brasil S/A - Bancoob										')), 'short_name' => ucwords(strtolower('Banco Cooperativo do Brasil - Bancoob		')),]);
        Bank::create(['bank_code' => 748, 'name' => ucwords(strtolower('Banco Cooperativo Sicredi S. A.													')), 'short_name' => ucwords(strtolower('Banco Cooperativo Sicredi					')),]);
        Bank::create(['bank_code' => 222, 'name' => ucwords(strtolower('Banco Credit Agrícole Brasil S.A.												')), 'short_name' => ucwords(strtolower('Banco Credit Agrícole Brasil				')),]);
        Bank::create(['bank_code' => 505, 'name' => ucwords(strtolower('Banco Credit Suisse (Brasil) S.A.												')), 'short_name' => ucwords(strtolower('Banco Credit Suisse (Brasil)				')),]);
        Bank::create(['bank_code' => 69, 'name' => ucwords(strtolower('Banco Crefisa S.A.																')), 'short_name' => ucwords(strtolower('Banco Crefisa								')),]);
        Bank::create(['bank_code' => 3, 'name' => ucwords(strtolower('Banco da Amazônia S.A.															')), 'short_name' => ucwords(strtolower('Banco da Amazônia							')),]);
        Bank::create(['bank_code' => 83, 'name' => ucwords(strtolower('Banco da China Brasil S.A.														')), 'short_name' => ucwords(strtolower('Banco da China Brasil						')),]);
        Bank::create(['bank_code' => 707, 'name' => ucwords(strtolower('Banco Daycoval S.A.																')), 'short_name' => ucwords(strtolower('Banco Daycoval								')),]);
        Bank::create(['bank_code' => 70, 'name' => ucwords(strtolower('Banco de Brasília S.A.															')), 'short_name' => ucwords(strtolower('Banco de Brasília							')),]);
        Bank::create(['bank_code' => 300, 'name' => ucwords(strtolower('Banco de la Nacion Argentina													')), 'short_name' => ucwords(strtolower('Banco de la Nacion Argentina				')),]);
        Bank::create(['bank_code' => 495, 'name' => ucwords(strtolower('Banco de La Provincia de Buenos Aires											')), 'short_name' => ucwords(strtolower('Banco de La Provincia de Buenos Aires		')),]);
        Bank::create(['bank_code' => 494, 'name' => ucwords(strtolower('Banco de La Republica Oriental del Uruguay										')), 'short_name' => ucwords(strtolower('Banco de La Republica Oriental del Uruguay	')),]);
        Bank::create(['bank_code' => 1, 'name' => ucwords(strtolower('Banco do Brasil S.A.															')), 'short_name' => ucwords(strtolower('Banco do Brasil							')),]);
        Bank::create(['bank_code' => 47, 'name' => ucwords(strtolower('Banco do Estado de Sergipe S.A.													')), 'short_name' => ucwords(strtolower('Banco do Estado de Sergipe					')),]);
        Bank::create(['bank_code' => 37, 'name' => ucwords(strtolower('Banco do Estado do Pará S.A.													')), 'short_name' => ucwords(strtolower('Banco do Estado do Pará					')),]);
        Bank::create(['bank_code' => 41, 'name' => ucwords(strtolower('Banco do Estado do Rio Grande do Sul S.A.										')), 'short_name' => ucwords(strtolower('Banco do Estado do Rio Grande do Sul		')),]);
        Bank::create(['bank_code' => 4, 'name' => ucwords(strtolower('Banco do Nordeste do Brasil S.A.												')), 'short_name' => ucwords(strtolower('Banco do Nordeste do Brasil				')),]);
        Bank::create(['bank_code' => 265, 'name' => ucwords(strtolower('Banco Fator S.A.																')), 'short_name' => ucwords(strtolower('Banco Fator								')),]);
        Bank::create(['bank_code' => 224, 'name' => ucwords(strtolower('Banco Fibra S.A.																')), 'short_name' => ucwords(strtolower('Banco Fibra								')),]);
        Bank::create(['bank_code' => 626, 'name' => ucwords(strtolower('Banco Ficsa S. A.																')), 'short_name' => ucwords(strtolower('Banco Ficsa								')),]);
        Bank::create(['bank_code' => 94, 'name' => ucwords(strtolower('Banco Finaxis S.A.																')), 'short_name' => ucwords(strtolower('Banco Finaxis								')),]);
        Bank::create(['bank_code' => 612, 'name' => ucwords(strtolower('Banco Guanabara S.A.															')), 'short_name' => ucwords(strtolower('Banco Guanabara							')),]);
        Bank::create(['bank_code' => 12, 'name' => ucwords(strtolower('Banco Inbursa S.A.																')), 'short_name' => ucwords(strtolower('Banco Inbursa								')),]);
        Bank::create(['bank_code' => 604, 'name' => ucwords(strtolower('Banco Industrial do Brasil S.A.													')), 'short_name' => ucwords(strtolower('Banco Industrial do Brasil					')),]);
        Bank::create(['bank_code' => 653, 'name' => ucwords(strtolower('Banco Indusval S. A.															')), 'short_name' => ucwords(strtolower('Banco Indusval								')),]);
        Bank::create(['bank_code' => 77, 'name' => ucwords(strtolower('Banco Inter S.A.																')), 'short_name' => ucwords(strtolower('Banco Inter								')),]);
        Bank::create(['bank_code' => 249, 'name' => ucwords(strtolower('Banco Investcred Unibanco S.A.													')), 'short_name' => ucwords(strtolower('Banco Investcred Unibanco					')),]);
        Bank::create(['bank_code' => 184, 'name' => ucwords(strtolower('Banco Itaú BBA S.A.																')), 'short_name' => ucwords(strtolower('Banco Itaú BBA S.A.						')),]);
        Bank::create(['bank_code' => 29, 'name' => ucwords(strtolower('Banco Itaú Consignado S.A.														')), 'short_name' => ucwords(strtolower('Banco Itaú Consignado						')),]);
        Bank::create(['bank_code' => 479, 'name' => ucwords(strtolower('Banco ItauBank S.A.																')), 'short_name' => ucwords(strtolower('Banco ItauBank								')),]);
        Bank::create(['bank_code' => 376, 'name' => ucwords(strtolower('Banco J. P. Morgan S. A.														')), 'short_name' => ucwords(strtolower('Banco J. P. Morgan							')),]);
        Bank::create(['bank_code' => 74, 'name' => ucwords(strtolower('Banco J. Safra S.A.																')), 'short_name' => ucwords(strtolower('Banco J. Safra								')),]);
        Bank::create(['bank_code' => 217, 'name' => ucwords(strtolower('Banco John Deere S.A.															')), 'short_name' => ucwords(strtolower('Banco John Deere							')),]);
        Bank::create(['bank_code' => 76, 'name' => ucwords(strtolower('Banco KDB do Brasil S.A.														')), 'short_name' => ucwords(strtolower('Banco KDB do Brasil						')),]);
        Bank::create(['bank_code' => 757, 'name' => ucwords(strtolower('Banco Keb Hana do Brasil S. A.													')), 'short_name' => ucwords(strtolower('Banco Keb Hana do Brasil					')),]);
        Bank::create(['bank_code' => 600, 'name' => ucwords(strtolower('Banco Luso Brasileiro S.A.														')), 'short_name' => ucwords(strtolower('Banco Luso Brasileiro						')),]);
        Bank::create(['bank_code' => 243, 'name' => ucwords(strtolower('Banco Máxima S.A.																')), 'short_name' => ucwords(strtolower('Banco Máxima								')),]);
        Bank::create(['bank_code' => 389, 'name' => ucwords(strtolower('Banco Mercantil do Brasil S.A.													')), 'short_name' => ucwords(strtolower('Banco Mercantil do Brasil					')),]);
        Bank::create(['bank_code' => 370, 'name' => ucwords(strtolower('Banco Mizuho do Brasil S.A.														')), 'short_name' => ucwords(strtolower('Banco Mizuho do Brasil						')),]);
        Bank::create(['bank_code' => 746, 'name' => ucwords(strtolower('Banco Modal S.A.																')), 'short_name' => ucwords(strtolower('Banco Modal								')),]);
        Bank::create(['bank_code' => 66, 'name' => ucwords(strtolower('Banco Morgan Stanley S. A.														')), 'short_name' => ucwords(strtolower('Banco Morgan Stanley						')),]);
        Bank::create(['bank_code' => 456, 'name' => ucwords(strtolower('Banco MUFG Brasil S.A.															')), 'short_name' => ucwords(strtolower('Banco MUFG Brasil							')),]);
        Bank::create(['bank_code' => 7, 'name' => ucwords(strtolower('Banco Nacional de Desenvolvimento Econômico e Social BNDES						')), 'short_name' => ucwords(strtolower('BNDES										')),]);
        Bank::create(['bank_code' => 169, 'name' => ucwords(strtolower('Banco Olé Bonsucesso Consignado S.A.											')), 'short_name' => ucwords(strtolower('Banco Olé Bonsucesso Consignado			')),]);
        Bank::create(['bank_code' => 79, 'name' => ucwords(strtolower('Banco Original do Agronegócio S.A.												')), 'short_name' => ucwords(strtolower('Banco Original do Agronegócio				')),]);
        Bank::create(['bank_code' => 212, 'name' => ucwords(strtolower('Banco Original S.A.																')), 'short_name' => ucwords(strtolower('Banco Original								')),]);
        Bank::create(['bank_code' => 712, 'name' => ucwords(strtolower('Banco Ourinvest S.A.															')), 'short_name' => ucwords(strtolower('Banco Ourinvest							')),]);
        Bank::create(['bank_code' => 623, 'name' => ucwords(strtolower('Banco Pan S.A.																	')), 'short_name' => ucwords(strtolower('Banco Pan									')),]);
        Bank::create(['bank_code' => 611, 'name' => ucwords(strtolower('Banco Paulista S.A.																')), 'short_name' => ucwords(strtolower('Banco Paulista								')),]);
        Bank::create(['bank_code' => 643, 'name' => ucwords(strtolower('Banco Pine S.A.																	')), 'short_name' => ucwords(strtolower('Banco Pine									')),]);
        Bank::create(['bank_code' => 747, 'name' => ucwords(strtolower('Banco Rabobank International Brasil S.A.										')), 'short_name' => ucwords(strtolower('Banco Rabobank International Brasil		')),]);
        Bank::create(['bank_code' => 633, 'name' => ucwords(strtolower('Banco Rendimento S.A.															')), 'short_name' => ucwords(strtolower('Banco Rendimento							')),]);
        Bank::create(['bank_code' => 741, 'name' => ucwords(strtolower('Banco Ribeirão Preto S.A.														')), 'short_name' => ucwords(strtolower('Banco Ribeirão Preto						')),]);
        Bank::create(['bank_code' => 120, 'name' => ucwords(strtolower('Banco Rodobens SA																')), 'short_name' => ucwords(strtolower('Banco Rodobens								')),]);
        Bank::create(['bank_code' => 422, 'name' => ucwords(strtolower('Banco Safra S.A.																')), 'short_name' => ucwords(strtolower('Banco Safra								')),]);
        Bank::create(['bank_code' => 33, 'name' => ucwords(strtolower('BANCO SANTANDER BRASIL S.A.														')), 'short_name' => ucwords(strtolower('BANCO SANTANDER BRASIL						')),]);
        Bank::create(['bank_code' => 743, 'name' => ucwords(strtolower('Banco Semear S.A.																')), 'short_name' => ucwords(strtolower('Banco Semear								')),]);
        Bank::create(['bank_code' => 754, 'name' => ucwords(strtolower('Banco Sistema S.A.																')), 'short_name' => ucwords(strtolower('Banco Sistema								')),]);
        Bank::create(['bank_code' => 630, 'name' => ucwords(strtolower('Banco Smartbank S.A.															')), 'short_name' => ucwords(strtolower('Banco Smartbank							')),]);
        Bank::create(['bank_code' => 366, 'name' => ucwords(strtolower('Banco Société Générale Brasil S.A.												')), 'short_name' => ucwords(strtolower('Banco Société Générale Brasil				')),]);
        Bank::create(['bank_code' => 637, 'name' => ucwords(strtolower('Banco Sofisa S. A.																')), 'short_name' => ucwords(strtolower('Banco Sofisa								')),]);
        Bank::create(['bank_code' => 464, 'name' => ucwords(strtolower('Banco Sumitomo Mitsui Brasileiro S.A.											')), 'short_name' => ucwords(strtolower('Banco Sumitomo Mitsui Brasileiro			')),]);
        Bank::create(['bank_code' => 82, 'name' => ucwords(strtolower('Banco Topazio S.A.																')), 'short_name' => ucwords(strtolower('Banco Topazio								')),]);
        Bank::create(['bank_code' => 634, 'name' => ucwords(strtolower('Banco Triângulo S.A.															')), 'short_name' => ucwords(strtolower('Banco Triângulo							')),]);
        Bank::create(['bank_code' => 18, 'name' => ucwords(strtolower('Banco Tricury S.A.																')), 'short_name' => ucwords(strtolower('Banco Tricury								')),]);
        Bank::create(['bank_code' => 655, 'name' => ucwords(strtolower('Banco Votorantim S.A.															')), 'short_name' => ucwords(strtolower('Banco Votorantim							')),]);
        Bank::create(['bank_code' => 610, 'name' => ucwords(strtolower('Banco VR S.A.																	')), 'short_name' => ucwords(strtolower('Banco VR 									')),]);
        Bank::create(['bank_code' => 119, 'name' => ucwords(strtolower('Banco Western Union do Brasil S.A.												')), 'short_name' => ucwords(strtolower('Banco Western Union do Brasil				')),]);
        Bank::create(['bank_code' => 124, 'name' => ucwords(strtolower('Banco Woori Bank do Brasil S.A.													')), 'short_name' => ucwords(strtolower('Banco Woori Bank do Brasil					')),]);
        Bank::create(['bank_code' => 81, 'name' => ucwords(strtolower('BancoSeguro S.A.																')), 'short_name' => ucwords(strtolower('Banco Seguro								')),]);
        Bank::create(['bank_code' => 21, 'name' => ucwords(strtolower('Banestes S.A. Banco do Estado do Espírito Santo									')), 'short_name' => ucwords(strtolower('Banestes									')),]);
        Bank::create(['bank_code' => 104, 'name' => ucwords(strtolower('Caixa Econômica Federal															')), 'short_name' => ucwords(strtolower('Caixa Econômica Federal					')),]);
        Bank::create(['bank_code' => 477, 'name' => ucwords(strtolower('Citibank N.A.																	')), 'short_name' => ucwords(strtolower('Citibank									')),]);
        Bank::create(['bank_code' => 136, 'name' => ucwords(strtolower('Confederação Nacional das Cooperativas Centrais Unicred Ltda – Unicred do Brasil')), 'short_name' => ucwords(strtolower('Unicred do Brasil							')),]);
        Bank::create(['bank_code' => 60, 'name' => ucwords(strtolower('Confidence Corretora de Câmbio S.A.                                             ')), 'short_name' => ucwords(strtolower('Confidence Corretora de Câmbio				')),]);
        Bank::create(['bank_code' => 341, 'name' => ucwords(strtolower('Itaú Unibanco S.A.																')), 'short_name' => ucwords(strtolower('Itaú Unibanco								')),]);
        Bank::create(['bank_code' => 652, 'name' => ucwords(strtolower('Itaú Unibanco Holding S.A.														')), 'short_name' => ucwords(strtolower('Itaú Unibanco Holding						')),]);
        Bank::create(['bank_code' => 323, 'name' => ucwords(strtolower('MercadoPago.com Representações Ltda.											')), 'short_name' => ucwords(strtolower('MercadoPago.com Representações				')),]);
        Bank::create(['bank_code' => 260, 'name' => ucwords(strtolower('Nu Pagamentos S.A.																')), 'short_name' => ucwords(strtolower('Nu Pagamentos - Nubank						')),]);
        Bank::create(['bank_code' => 613, 'name' => ucwords(strtolower('Omni Banco S.A.																	')), 'short_name' => ucwords(strtolower('Omni Banco									')),]);
        Bank::create(['bank_code' => 290, 'name' => ucwords(strtolower('Pagseguro Internet S.A.															')), 'short_name' => ucwords(strtolower('Pagseguro Internet							')),]);
        Bank::create(['bank_code' => 183, 'name' => ucwords(strtolower('Socred S.A. - Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno P')), 'short_name' => ucwords(strtolower('Socred										')),]);
        Bank::create(['bank_code' => 299, 'name' => ucwords(strtolower('Sorocred - Crédito, Financiamento e Investimento S/A							')), 'short_name' => ucwords(strtolower('Sorocred									')),]);
        Bank::create(['bank_code' => 102, 'name' => ucwords(strtolower('XP Investimentos Corretora de Câmbio Títulos e Valores Mobiliários S.A.			')), 'short_name' => ucwords(strtolower('XP Investimentos 							')),]);
    }
}
