<?php

namespace Database\Seeders;

use App\Models\Tooth;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TeethTableSeeder extends Seeder
{
    public function run()
    {
        Tooth::create(['tooth_code'  =>  11, 'tooth_name' => ucfirst(strtolower('INCISIVO CENTRAL SUPERIOR DIREITO          ')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  12, 'tooth_name' => ucfirst(strtolower('INCISIVO LATERAL SUPERIOR DIREITO			')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  13, 'tooth_name' => ucfirst(strtolower('CANINO SUPERIOR DIREITO					')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  14, 'tooth_name' => ucfirst(strtolower('PRIMEIRO PRE-MOLAR SUPERIOR DIREITO		')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  15, 'tooth_name' => ucfirst(strtolower('SEGUNDO PRE-MOLAR SUPERIOR DIREITO			')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  16, 'tooth_name' => ucfirst(strtolower('PRIMEIRO MOLAR SUPERIOR DIREITO			')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  17, 'tooth_name' => ucfirst(strtolower('SEGUNDO MOLAR SUPERIOR DIREITO				')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  18, 'tooth_name' => ucfirst(strtolower('TERCEIRO MOLAR SUPERIOR DIREITO			')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  21, 'tooth_name' => ucfirst(strtolower('INCISIVO CENTRAL SUPERIOR ESQUERDO			')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  22, 'tooth_name' => ucfirst(strtolower('INCISIVO LATERAL SUPERIOR ESQUERDO			')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  23, 'tooth_name' => ucfirst(strtolower('CANINO SUPERIOR ESQUERDO					')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  24, 'tooth_name' => ucfirst(strtolower('PRIMEIRO PRE-MOLAR SUPERIOR ESQUERDO		')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  25, 'tooth_name' => ucfirst(strtolower('SEGUNDO PRE-MOLAR SUPERIOR ESQUERDO		')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  26, 'tooth_name' => ucfirst(strtolower('PRIMEIRO MOLAR SUPERIOR ESQUERDO			')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  27, 'tooth_name' => ucfirst(strtolower('SEGUNDO MOLAR SUPERIOR ESQUERDO			')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  28, 'tooth_name' => ucfirst(strtolower('TERCEIRO MOLAR SUPERIOR ESQUERDO			')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  31, 'tooth_name' => ucfirst(strtolower('INCISIVO CENTRAL INFERIOR ESQUERDO			')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  32, 'tooth_name' => ucfirst(strtolower('INCISIVO LATERAL INFERIOR ESQUERDO			')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  33, 'tooth_name' => ucfirst(strtolower('CANINO INFERIOR ESQUERDO					')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  34, 'tooth_name' => ucfirst(strtolower('PRIMEIRO PRE-MOLAR INFERIOR ESQUERDO		')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  35, 'tooth_name' => ucfirst(strtolower('SEGUNDO PRE-MOLAR INFERIOR ESQUERDO		')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  36, 'tooth_name' => ucfirst(strtolower('PRIMEIRO MOLAR INFERIOR ESQUERDO			')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  37, 'tooth_name' => ucfirst(strtolower('SEGUNDO MOLAR INFERIOR ESQUERDO			')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  38, 'tooth_name' => ucfirst(strtolower('TERCEIRO MOLAR INFERIOR ESQUERDO			')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  41, 'tooth_name' => ucfirst(strtolower('INCISIVO CENTRAL INFERIOR DIREITO			')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  42, 'tooth_name' => ucfirst(strtolower('INCISIVO LATERAL INFERIOR DIREITO			')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  43, 'tooth_name' => ucfirst(strtolower('CANINO INFERIOR DIREITO					')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  44, 'tooth_name' => ucfirst(strtolower('PRIMEIRO PRE-MOLAR INFERIOR DIREITO		')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  45, 'tooth_name' => ucfirst(strtolower('SEGUNDO PRE-MOLAR INFERIOR DIREITO			')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  46, 'tooth_name' => ucfirst(strtolower('PRIMEIRO MOLAR INFERIOR DIREITO			')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  47, 'tooth_name' => ucfirst(strtolower('SEGUNDO MOLAR INFERIOR DIREITO				')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  48, 'tooth_name' => ucfirst(strtolower('TERCEIRO MOLAR INFERIOR DIREITO			')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  51, 'tooth_name' => ucfirst(strtolower('INCISIVO CENTRAL DECIDUO SUPERIOR DIREITO	')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  52, 'tooth_name' => ucfirst(strtolower('INCISIVO LATERAL DECIDUO SUPERIOR DIREITO	')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  53, 'tooth_name' => ucfirst(strtolower('CANINO DECIDUO SUPERIOR DIREITO			')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  54, 'tooth_name' => ucfirst(strtolower('PRIMEIRO MOLAR DECIDUO SUPERIOR DIREITO	')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  55, 'tooth_name' => ucfirst(strtolower('SEGUNDO MOLAR DECIDUO SUPERIOR DIREITO		')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  61, 'tooth_name' => ucfirst(strtolower('INCISIVO CENTRAL DECIDUO SUPERIOR ESQUERDO	')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  62, 'tooth_name' => ucfirst(strtolower('INCISIVO LATERAL DECIDUO SUPERIOR ESQUERDO	')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  63, 'tooth_name' => ucfirst(strtolower('CANINO DECIDUO SUPERIOR ESQUERDO			')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  64, 'tooth_name' => ucfirst(strtolower('PRIMEIRO MOLAR DECIDUO SUPERIOR ESQUERDO	')), 'mesial' => true, 'distal' => true, 'lingual' => null, 'palatal' => true, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  65, 'tooth_name' => ucfirst(strtolower('SEGUNDO MOLAR DECIDUO SUPERIOR ESQUERDO	')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => true, 'cervical' => true, 'incisal' => true, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  71, 'tooth_name' => ucfirst(strtolower('INCISIVO CENTRAL DECIDUO INFERIOR ESQUERDO	')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  72, 'tooth_name' => ucfirst(strtolower('INCISIVO LATERAL DECIDUO INFERIOR ESQUERDO	')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  73, 'tooth_name' => ucfirst(strtolower('CANINO DECIDUO INFERIOR ESQUERDO			')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  74, 'tooth_name' => ucfirst(strtolower('PRIMEIRO MOLAR DECIDUO INFERIOR ESQUERDO	')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  75, 'tooth_name' => ucfirst(strtolower('SEGUNDO MOLAR DECIDUO INFERIOR ESQUERDO	')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  81, 'tooth_name' => ucfirst(strtolower('INCISIVO CENTRAL DECIDUO INFERIOR DIREITO	')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  82, 'tooth_name' => ucfirst(strtolower('INCISIVO LATERAL DECIDUO INFERIOR DIREITO	')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  83, 'tooth_name' => ucfirst(strtolower('CANINO DECIDUO INFERIOR DIREITO			')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => true, 'occlusal' => null, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  84, 'tooth_name' => ucfirst(strtolower('PRIMEIRO MOLAR DECIDUO INFERIOR DIREITO	')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  =>  85, 'tooth_name' => ucfirst(strtolower('SEGUNDO MOLAR DECIDUO INFERIOR DIREITO		')), 'mesial' => true, 'distal' => true, 'lingual' => true, 'palatal' => null, 'cervical' => true, 'incisal' => null, 'occlusal' => true, 'buccal' => true, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  => 100, 'tooth_name' => ucfirst(strtolower('BOCA TOTAL									')), 'mesial' => null, 'distal' => null, 'lingual' => null, 'palatal' => null, 'cervical' => null, 'incisal' => null, 'occlusal' => null, 'buccal' => null, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  => 101, 'tooth_name' => ucfirst(strtolower('PRIMEIRO QUADRANTE (SUPERIOR DIREITO)		')), 'mesial' => null, 'distal' => null, 'lingual' => null, 'palatal' => null, 'cervical' => null, 'incisal' => null, 'occlusal' => null, 'buccal' => null, 'multiple_teeth' => true,]);
        Tooth::create(['tooth_code'  => 102, 'tooth_name' => ucfirst(strtolower('SEGUNDO QUADRANTE (SUPERIOR ESQUERDO)		')), 'mesial' => null, 'distal' => null, 'lingual' => null, 'palatal' => null, 'cervical' => null, 'incisal' => null, 'occlusal' => null, 'buccal' => null, 'multiple_teeth' => true,]);
        Tooth::create(['tooth_code'  => 103, 'tooth_name' => ucfirst(strtolower('TERCEIRO QUADRANTE (INFERIOR ESQUERDO)		')), 'mesial' => null, 'distal' => null, 'lingual' => null, 'palatal' => null, 'cervical' => null, 'incisal' => null, 'occlusal' => null, 'buccal' => null, 'multiple_teeth' => true,]);
        Tooth::create(['tooth_code'  => 104, 'tooth_name' => ucfirst(strtolower('QUARTO QUADRANTE (INFERIOR DIREITO)		')), 'mesial' => null, 'distal' => null, 'lingual' => null, 'palatal' => null, 'cervical' => null, 'incisal' => null, 'occlusal' => null, 'buccal' => null, 'multiple_teeth' => true,]);
        Tooth::create(['tooth_code'  => 105, 'tooth_name' => ucfirst(strtolower('REGIAO SUPERIOR (ARCO SUPERIOR)			')), 'mesial' => null, 'distal' => null, 'lingual' => null, 'palatal' => null, 'cervical' => null, 'incisal' => null, 'occlusal' => null, 'buccal' => null, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  => 106, 'tooth_name' => ucfirst(strtolower('REGIAO INFERIOR (ARCO INFERIOR)			')), 'mesial' => null, 'distal' => null, 'lingual' => null, 'palatal' => null, 'cervical' => null, 'incisal' => null, 'occlusal' => null, 'buccal' => null, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  => 110, 'tooth_name' => ucfirst(strtolower('REGIÃO DOS OLHOS							')), 'mesial' => null, 'distal' => null, 'lingual' => null, 'palatal' => null, 'cervical' => null, 'incisal' => null, 'occlusal' => null, 'buccal' => null, 'multiple_teeth' => null,]);
        Tooth::create(['tooth_code'  => 111, 'tooth_name' => ucfirst(strtolower('FACE										')), 'mesial' => null, 'distal' => null, 'lingual' => null, 'palatal' => null, 'cervical' => null, 'incisal' => null, 'occlusal' => null, 'buccal' => null, 'multiple_teeth' => null,]);
    }
}